image: node:10

cache:
  paths:
    - node_modules/

before_script:
  - yarn

pages:
  stage: deploy
  script:
    - yarn build
    - rm -fr public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
